### ISSUE TITLE
현재 나의 위치를 확인할 수 있도록 필요한 자료 학습(MapKit, CoreLocation)

### ISSUE THREAD

**Issue by whrlgus** [boostcamp-2020/Project18-B-iOS-BoostRunClub#17]

**Comment by SHIVVVPP** [comment]
[Handling Location Events in the Background](https://hackmd.io/YLsSoHg0TzaX6h95ujDucA)
[MapKit Tutorial](https://www.innofied.com/implement-location-tracking-using-mapkit-in-swift/)
[Swift iOS CLLocationManager All-In-One](https://itnext.io/swift-ios-cllocationmanager-all-in-one-b786ffd37e4a)
[SwiftBackgroundLocation](https://github.com/yoman07/SwiftBackgroundLocation)
[BackgroundTask 정리](https://lemon-dev.tistory.com/entry/iOS-BackgroundTask-Framework-%EA%B0%84%EB%8B%A8-%EC%A0%95%EB%A6%AC)

**Comment by seoulboy** [comment]
> [Handling Location Events in the Background](https://hackmd.io/YLsSoHg0TzaX6h95ujDucA)
> [MapKit Tutorial](https://www.innofied.com/implement-location-tracking-using-mapkit-in-swift/)
> [Swift iOS CLLocationManager All-In-One](https://itnext.io/swift-ios-cllocationmanager-all-in-one-b786ffd37e4a)
> [SwiftBackgroundLocation](https://github.com/yoman07/SwiftBackgroundLocation)
> [BackgroundTask 정리](https://lemon-dev.tistory.com/entry/iOS-BackgroundTask-Framework-%EA%B0%84%EB%8B%A8-%EC%A0%95%EB%A6%AC)

여기 있는 문서들 한번 쭉 흝어볼게요  감사합니다

**Comment by SHIVVVPP** [comment]
[Combine & CoreLocation, Part 1 – Publishers & Delegates](https://learningswift.brightdigit.com/combine-corelocation-publishers-delegates/)
[Combine & CoreLocation, Part 2 – Receiving & Handling Events](https://learningswift.brightdigit.com/combine-corelocation-receiving-handling-events/)
[Combine & CoreLocation, Part 3 – Integrations with flatMap](https://learningswift.brightdigit.com/combine-corelocation-swiftui-delegates/)
