### ISSUE TITLE
디테일

### ISSUE THREAD

**Issue by seoulboy** [boostcamp-2020/Project18-B-iOS-BoostRunClub#24]
러닝 준비 화면

- [ ] 시작 버튼 홀드 시 : 불투명하게 변경 
- [ ] 목표설정 버튼 홀드시 : 사이즈가 줄었다가 작아짐
- [x] 지도 터치 막기
- [x] 지우기 버튼이 골 타입 설정 상태에 따라 보이거나 안보이게 하기
- [x] 골타입 선택 되었을 때 지도에 목표 입력 수치화면으로 넘어갈 수 있는 버튼 보이게 하기

**Comment by whrlgus** [comment]
[ ] 목표 설정 화면 아래부분 corner radius 적용된 부분 수정
![image](https://user-images.githubusercontent.com/21030956/100164462-425d1e80-2efb-11eb-88d2-8866d608e89e.png)
