### ISSUE TITLE
<Combine Study> AnyPublisher, CurrentValueSubject, PassThroughSubject에 대해 조사한다

### ISSUE THREAD

**Issue by seoulboy** [boostcamp-2020/Project18-B-iOS-BoostRunClub#36]
### 의논거리 🤔 
- 각각의 Publisher는 언제 어떻게 사용하는게 알맞는지 알아본다

### 관련 PR or Issue Number

- Issue : #35

**Comment by SHIVVVPP** [comment]
### AnyPublisher

다른 publisher로부터의 publisher를 wrapping 합니다.

AnyPulisher는 Publisher의 구체 구현체이며 프로퍼티를 가지지 않습니다.

upstream publisher로부터의 elements나 completion value를 전달합니다.

AnyPublisher는 보통 다른 Module 처럼 API 경계 밖으로 부터 오는 publisher의 구체적인 타입을 노출시키고 싶지 않을 때 사용합니다.

> 추가로 Subject를 AnyPublisher로 wrapping 시키면 호출자가 'send(_:)' 메서드를 사용하는 것을 막을 수 있습니다.

### CurrentValueSubject

A subject that wraps a single value and publishes a new element whenever the value changes.

하나의 값을 wrapping 하고 값이 변경될 때 마다 새로운 element를 publish 합니다.

PassthroughSubject와 달리 CurrentValueSubject는 가장 최근의 값을 버퍼에 보관합니다.

>  CurrentValueSubject에서 `send(_:)` 를 사용하면 현재 value도 업데이트 됩니다.

**요약**

- 구독하자마자 현재 값이 발행됨
- 무조건 초기값을 지정해야 함

### PassthroughSubject

downstream subscriber에게 elements를 broadcast 하는 개체입니다.

PassthroughSubject는 기존 명령형 코드를 Combine 모델에 적용하는 편리한 방법을 제공합니다.

CurrentValueSubject와 다르게 최근 값에 대한 initial value 나 buffer를 가지고 있지 않습니다.

PassthroughSubject는 Subscriber가 없거나 demand가 0이라면 값을 drop 합니다.

**요약**

- 구독 후 값이 들어왔을 때만 발행됨
- 같은 값이 또 들어와도 발행됨

### 사용중인 이유

현재 저희가 사용하는 ViewModel에서는 Output으로 고정 값이 아니라 유동적이어야 될 필요가 있는 프로퍼티에 대해  `CurrentValueSubject` `PassthroughSubject` 를 사용합니다.

`CurrentValueSubject` 의 경우 ViewModel이 값을 가지고 그 값을 바인딩 하기 위해 사용되며

`PassthroughSubject`는 주로 ViewModel에서 외부로 Signal을 주거나 외부로부터 들어오는 값을 처리하고 다시 Publish 하기 위해 사용합니다.

### CurrentValueSubject

`CurrentValueSubject` 같은 경우 @Published 어노테이션을 ViewModel의 속성 앞에 붙여 Observing 가능한 개체로 만드는 것으로 대체 가능하나

저희의 ViewModel에서 이러한 Observing 가능한 개체들은 ~Output으로 추상화 되어있기 때문에

Protocol에서 @Published를 붙일 수 없어

```swift
protocol ~Output {
	valueObservable: Published<Value>.Publisher { get }
}

class ~ViewModel: ~Output {
    @Published private(set) var value: Value
    var valueObservable: Published<Value>.Publisher { $value }
}
```

위와 같은 형태로 구현해야 하기 때문에

protocol과 이를 채택한 concreate class에서 좀더 사용하기 쉽도록 CurrentValueSubject를 사용합니다.

```swift
protocol ~Output {
	valueObservable: CurrentValueSubject<Value> { get }
}

class ~ViewModel: ~Output {
    private(set) var valueObservable = CurrentValueSubject<Value>()
}
```

@Published 같은 경우 값을 대입하여 변경해도 바로 Publish 된다는 편리함이 있고

CurrentValueSubject 같은 경우 `send(:_)` 메서드를 통해 변경해야 한다는 불편함이 있습니다.

> 하지만 이것도 `=` 대입으로 처리할 경우는 명시적이지 않지만 
>
> `send` 를 통해 값을 처리하면 이 개체가 Publish 하는 개체임을 알 수 있다는 장점도 있는 것 같습니다.

### PassthroughSubject

`PassthroughSubject` 같은 경우 저희 프로젝트에서는 주로

값을 가지고 있을 필요가 없고 전달하기만 하면 되는 

외부 Service (ex LocationProvider) 로부터 오는 값을 View에 전달,

애니메이션을 실행해라, 다른 화면을 Present 해라 와 같은 Signal 처리에 사용합니다.

(Void를 Passthrough 하기도 합니다.)

요약하자면,

단지 **전달** 하는 매개체 입니다.

SetGoalType 화면을 보여주라는 신호를 보낸다고 할 때

PassthroughSubject를 이용한 코드는 다음과 같습니다.

```swift
protocol ~Output {
	showSetGoalTypeSheetSignal: PassthroughSubject<Value> { get }
}

class ~ViewModel: ~Output {
    private(set) var showSetGoalTypeSheetSignal = PassthroughSubject<Value>()
    
    func didTapShowGoalTypeButton() {
        showSetGoalTypeSheetSignal.send(value)
    }
}
```



AnyPublisher는 단순히 다른 Publisher를 wrapping 할 때 사용하는 것이기 때문에 이 경우 사용하는 것이 무리라고생각되며

주로 함수의 return 형태로 다른 Publisher로부터 들어오는 값을 처리할 때 사용하는 것이 바람직하다고 생각됩니다.

**Comment by whrlgus** [comment]
### Publisher [docs](https://developer.apple.com/documentation/combine/publisher)

- **Protocol**
- 다수의 Subscriber 인스턴스에 인자를 전달할 수 있다.
- <Output, Failure> 타입은 Subscriber의 <Input, Failure> 타입과 일치해야 한다.
- Publisher protocol을 직접 구현해도 되지만, 이를 위해 Combine Framework에서 여러가지 type을 제공해 준다.
  - Subject의 concrete subclass인,  PassthroughSubject의 `send(_:)` 메소드를 호출하여 값을 전달할 수 있다.
  - CurrentValueSubject를 이용하면, 내제된 값이 변경될 때마다 값을 발행할 수 있다.
  - `@Published` annotation을 프로퍼티에 사용하면, 해당 프로퍼티는 값이 갱신될 때마다 값을 발행하는 publisher를 얻게 된다. 



### AnyPublisher [docs](https://developer.apple.com/documentation/combine/anypublisher)

- **Structure**
- Upstream publisher로부터 받은 최종적인 인자를 전달하는 역할을 한다.
- 다른 publisher를 감싸서 노출할 필요가 없는 자세한 type을 숨길 수 있다.
- 호출하는 곳에서 `send(_:)` method는 호출할 수 없다.
- Type erasure를 사용하면, client에 영향을 주지 않고 내재된 publisher 구현체를 변경할 수 있다.



### Subscriber [docs](https://developer.apple.com/documentation/combine/subscriber)

- **Protocol**
- publisher로부터 input을 받을 수 있는 type을 선언한다.
- Combine은 Publisher에 사용하는 operator 유형의 subscriber를 제공한다.
  - `sink(receiveCompletion:receiveValue:)` 
  - `assign(to:on:)` 



### Subject [docs](https://developer.apple.com/documentation/combine/subject)

- **Protocol**

- 외부에서 method를 호출하게 하여 인자를 발행하는 publisher이다.
- `send(_:)` 메소드를 호출하여 stream에 값을 주입할 수 있다.
- 존재하는 명령형(imperative)의  코드를 Combine 모델에 적용하는데 유용하게 사용할 수 있다.



### PassThroughSubject [docs](https://developer.apple.com/documentation/combine/passthroughsubject)

- **Class**

- Downstream subscriber로 인자를 전달(broadcast)하는 subject이다.

- [Subject](https://developer.apple.com/documentation/combine/subject) 프로토콜을 채택하며, 존재하는 명령형의 코드를 Combine 모델에 적용할 수 있도록 편리함을 제공한다. CurrentValueSubject와는 다르게 초기값이나 가장 최근 값을 발행하는 요소의 버퍼를 갖지 않는다. subscriber가 존재하지 않거나, 현재 demand가 zero라면 전달하는 값들을 버린다.



### CurrentValueSubject [docs](https://developer.apple.com/documentation/combine/currentvaluesubject)

- **Class**

- 단일 값을 감싸고(wrap) 있으며, 값이 변경될 때마다 새로운 값을 발행한다.
- PassthroughSubject와는 다르게 가장 최근 발행한 인자를 담는 버퍼가 존재한다.
- PassthroughSubject와 동일하게 `send(_:)` 를 호출하여 값을 발행하지만, CurrentValueSubject는 발행함과 동시에 값을 저장한다. 내부 프로퍼티인  `value` 에 직접 값을 할당하여 같은 일을 처리할 수도 있다. 



### AnyPublisher 활용

기존에 ViewController에서 UI를 갱신하기 위한 publisher를 새로 만들어 binding하여 사용했다.  이 로직을 ViewModel로 옮겨 ViewController는 ViewModel과 바인딩을 통해 UI 갱신하는 역할만 수행하도록 해줘야 한다.

```swift
// PrepareRunViewController
// func bindViewModel()
Publishers.CombineLatest(viewModel.outputs.goalTypeObservable, viewModel.outputs.goalValueObservable)
	.receive(on: DispatchQueue.main)
	.sink { [weak self] goalType, goalValue in
		if goalType == .none {
			self?.goalValueView.isHidden = true
		} else {
			self?.goalValueView.isHidden = false
			self?.goalValueView.setLabelText(goalValue: goalValue, goalUnit: goalType.unit)
		}
	}
	.store(in: &cancellables)
```



ViewModel에서 type erasure를 이용하여 노출할 필요가 없는 자세한 정보를 숨기고, client에서 필요한 정보만을 받을 수 있도록 publisher stream을 AnyPublisher 타입으로 감싼다. 이와 같이 하면, ViewController 와 같은 client에 영향을 주지 않고 `currentGoalInfo` 의 내부 로직을 변경할 수 있는 장점도 있다.

```swift
// PrepareRunViewModel
var currentGoalInfo: AnyPublisher<GoalInfo, Never> {
	Publishers.CombineLatest(goalTypeObservable, goalValueObservable)
		.map { goalType, goalValue in
			GoalInfo(goalType: goalType, goalValue: goalValue)
		}
		.eraseToAnyPublisher()
}

// PrepareRunViewController
// func bindViewModel()
viewModel.outputs.currentGoalInfo
	.receive(on: RunLoop.main)
	.sink { [weak self] goalInfo in
		if goalInfo.goalType == .none {
			self?.goalValueView.isHidden = true
		} else {
			self?.goalValueView.isHidden = false
			self?.goalValueView.setLabelText(goalValue: goalInfo.goalValue, goalUnit: goalInfo.goalType.unit)
		}
	}
	.store(in: &cancellables)
```

**Comment by SHIVVVPP** [comment]
goalValueView의 goalValue와 goalType 설정 로직을 나누는게 더 좋지 않을까요?

**Comment by seoulboy** [comment]
## Subjects 🙋‍♀️🙋‍♂️

#### 프로토콜은 Subscriber이며 동시에 Publisher이며 Value이다. 🤔

> 이게 무슨말인지 이해가 안된다면 . .👇
>
> A subject can receive values from an upstream publisher, and also can pass along these values to its downstream subscribers.
>
> **Subject는 업스트림 발행자로부터 값을 전달받을 수도 있고, 다운스트림 구독자에게 값을 전달할 수도 있다. 또 값을 가지고 있을 수도 있다.** 



Subjects 에는 2가지 종류가 있는데, 우선 그 중 하나인 PassThroughSubject로 만든 예시를 한번 보자.



아래는 `PassThroughSubject` 가 구독자 역할을 하는 모습이다.

```swift
// 발행자
let publisher = [1, 2, 3].publisher

// 구독자 역할을 할 passthroughsubject
let passThroughSubject = PassThroughSubject<Int, Never>()

// 둘을 엮으려면 - AnySubscriber(s: Subject)를 활용할 수 있다. 
// (PassThroughSubject는 Subject 프로토콜을 준수한다.)
let anySubscriber = AnySubscriber(passThroughSubject)

// PassThroguhSubject를 이용하여 구독관계가 성립된 모습 (Subject의 구독자 역할)
publisher.receive(subscriber: anySubscriber)
```



이번에는 발행자 역할을 하는 모습이다.

```swift
// 발행자 역할을 할 PassThroughSubject
let passThorughSubject = PassThroughSubject<Int, Never>()

// sink() 메서드를 통해 해당 passThroughSubject와 연결되어있는 다운스트림 구독자를 생성할 수 있다.
// 값을 구독자에게 내려다주기 때문에 여기서는 발행자 역할을 한다.
let newSubscriber = passthroughSubject
            .sink { value in
									print(value)
             }
```



이런식으로 subject는 두가지 역할을 다 할 수 있는 ~~SOLID 원칙에 위배되는~~ 고마운 친구.



위에서 Subject에는 두가지 종류가 있다고 했는데, 이제는 이 두가지에 대해 알아보자.



첫번째로 좀전에 예시에서 만났던 `PassThroughSubject` , 두번째로 `CurrentValueSubject` 가 있다.

둘다 공통적으로 Subject 프로토콜을 채택하여 앞서 보았듯이 발행자 및 구독자 역할을 소화해낼 수 있다.



발행자 역할의 관점에서 두 subject의 다른 점이 있다면 `CurrentValueSubject` 는 초기값이 있고, `PassThroughSubject` 는 초기값이 없고 발행을 시작한 시점부터 값이 있다는 점이다.



`CurrentValueSubject` 는 아래와 같이 생성시에 초기값을 담아야한다. 

```swift
let currentSubject = CurrentValueSubject<Int, Never>(99)
```



`PassThroughSubject` 는 생성시에는 초기값을 담을 수 없다.

```swift
let passthroughSubject = PassthroughSubject<Int, Never>()
```



이러한 둘의 차이때문에, 다음과 같은 차이가 파생된다. 

"CurrentValueSubject 는 구독이 시작되는 시점에 초기값이 게시가 되기 때문에 연결이 되자마자 값이 구독자에게 전달되지만, PassThroughSubject는 구독이 시작되고, 그 후에 값이 게시가 되었을 때 구독자에게 값이 전달된다."



이게 무슨말인지는 아래의 예시를 보면 한번에 이해가 갈 것이다. 우선은 `CurrentValueSubject` 의 동작을 살펴보자

```swift
// message 문자열 변수값을 담은 currentValueSubject를 생성한다. 여기서 message는 초기값이다.
let message = "넷플릭스 구독이 시작되었음을 알리는 메시지입니다. 서비스를 바로 이용하셔도 됩니다."
let currentValueSubject = CurrentValueSubject<String, Never>(message)

// sink()메서드를 통해 구독자를 바로 연결한다. 
// 구독자와 연결이 된 직후 발행자는 값을 게시하므로, currentValueSubject는 초기값인 message	값을 다운스트림 구독자에게 전달한다.
// 다운스트림 구독자는 해당 값을 받아서 print 한다.
let subscriber = currentValueSubject.sink { message
										print(message)
									}

// 두번째 값을 게시한다. - 구독자는 다시한번 전달받은 값을 print 한다
currentValueSubject.send("새로운 영화 및 드라마가 출시되었습니다. 지금 바로 확인해보세요!")


// - Output -
// "넷플릭스 구독이 시작되었음을 알리는 메시지입니다. 서비스를 바로 이용하셔도 됩니다."
// "새로운 영화 및 드라마가 출시되었습니다. 지금 바로 확인해보세요!"
```



`CurrentValueSubject`  는 초기값을 가지고, 구독이 시작되는 순간 값을 다운스트림 구독자에게 전달한다.



위와 같은 동작을 `PassThroughSubject`로 동일하게 하려면 어떻게 해야할까? 

앞서 말했듯이, `PassThroughSubject` 는 `CurrentValueSubject` 와 다르게 <u>초기값이 없다.</u>

그러므로 구독이 시작된 시점이 아닌 `PassThroughSubject` 가 값을 게시한 순간부터 값이 전달된다. 

이번에도 역시 예제를 보면 이해가 단번에 될 것이다.

```swift
let passThroughSubject = PassThroughSubject<String, Never>()

// sink()메서드를 통해 구독자를 바로 연결한다. 
// 구독자와 연결이 된 직후 발행자는 값을 게시하지만, PassThroughSubject는 초기값이 없기때문에 다운스트림 구독자에게 전달되는 값이 없다.
let subscriber = passThroughSubject.sink { message
										print(message)
									}


let messageA = "넷플릭스 구독이 시작되었음을 알리는 메시지입니다. 서비스를 바로 이용하셔도 됩니다."
let messageB = "새로운 영화 및 드라마가 출시되었습니다. 지금 바로 확인해보세요!"

// send()를 통해 값을 게시하여 값을 구독자에게 전달한다.
passThroughSubject.send(messageA)
passThroughSubject.send(messageB)


// - Output -
// "넷플릭스 구독이 시작되었음을 알리는 메시지입니다. 서비스를 바로 이용하셔도 됩니다."
// "새로운 영화 및 드라마가 출시되었습니다. 지금 바로 확인해보세요!"
```



#### Completion Event - 서비스 종료 🔚



Subject는 completion 이벤트를 받으면 더이상 값을 받지 않는다. 

이는 마치 월간 구독 서비스를 이용하는 구독자에게 서비스가 끝났음을 알리고, 구독 서비스는 새로운 월간 구독 상품을 출시한다. 서비스가 종료된 구독자는 더이상 해당 서비스의 구독 상품을 받아볼 수 없고,  마지막으로 받아본 상품을 가지고 있는 것 유사하다고 볼 수 있겠다. 



```swift
let currentValueSubject = CurrentValueSubject<Int, Never>(1)
print(currentValueSubject.value)
// 1

currentValueSubject.send(2)
print(currentValueSubject.value)
// 2

currentValueSubject.send(completion: .finished)

currentValueSubject.send(10)

print(currentValueSubject.value)
// 10이 아닌 2를 출력한다 
```



---



#### 장단점 ➕➖

##### Subject의 장점 :

- @Published 와는 다르게 Protocol 선언에 사용이 가능하다. (Property wrapper는 프로토콜 안에서 사용이 불가능하다)

- @Published 와는 다르게 error type 사용이 가능하다.



##### Subject의 단점:

- 코드가 약간 길어진다 (?)

> 이 부분에 대해서는 추가적인 조사가 필요하다 🧪
