### ISSUE TITLE
RunningTabFlowCoordinator를 제거하고 PrepareRunCoordinator를 상위로 올리는게 어떨까요?

### ISSUE THREAD

**Issue by SHIVVVPP** [boostcamp-2020/Project18-B-iOS-BoostRunClub#44]
### 의논거리 🤔 
RunningTapFlowCoordinator는 저희 프로젝트 초기 기획에서 PrepareRun과 Running Scene에 대한 Coordinator였지만
Running Scene이 AppCordinator 하위로 들어가게끔 되어
이제 RunningTapFlow -> PrepareRun 할 필요 없이
TapBarCoordinator에 바로 PrepareRun Coordinator를 두어도 될 것 같습니다.

> + 추가로 tabBarCoordinator이름을 변경하면 어떨까요.. ㅎ

**Comment by whrlgus** [comment]
네 저희 어제 구조를 바꿨으니 수정이 필요하죵 이따가 이름도 새로 같이 정해 봅시다
